"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Download, ExternalLink, FileLock2, Loader2, MessageSquareText, Save, Send, ShieldCheck, Trash2, UploadCloud, XCircle } from "lucide-react";
import { STATUS_OPTIONS, TWENTY_FIVE_MB } from "@/lib/constants";
import { formatDate, formatMoney, statusLabel } from "@/lib/format";
import { uploadPrivateFile } from "@/lib/upload-client";

export function AssignmentManager({ assignmentId, supabaseConfigured }: { assignmentId:string; supabaseConfigured:boolean }) {
  const [data,setData]=useState<any>(null);
  const [loading,setLoading]=useState(supabaseConfigured);
  const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState<{type:"success"|"error"|"info";text:string}|null>(null);
  const [comment,setComment]=useState("");
  const [uploadKind,setUploadKind]=useState<"preview"|"final">("preview");
  const [uploadFile,setUploadFile]=useState<File|null>(null);

  const load=useCallback(async()=>{if(!supabaseConfigured){setLoading(false);setNotice({type:"info",text:"Connect Supabase in Vercel before managing assignments."});return;}setLoading(true);try{const response=await fetch(`/api/admin/assignments/${assignmentId}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to load assignment.");setData(payload);}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to load assignment."});}finally{setLoading(false);}},[assignmentId,supabaseConfigured]);
  useEffect(()=>{void load();},[load]);

  async function request(method:"PATCH"|"POST",body:any){const response=await fetch(`/api/admin/assignments/${assignmentId}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Action failed.");return payload;}
  async function run(task:()=>Promise<any>,message:string){setBusy(true);setNotice(null);try{await task();setNotice({type:"success",text:message});await load();}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Action failed."});}finally{setBusy(false);}}

  async function saveOverview(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await run(()=>request("PATCH",{status:form.get("status"),progress:Number(form.get("progress")),quotedAmount:form.get("quotedAmount"),currency:form.get("currency"),finalMessage:form.get("finalMessage"),downloadUnlocked:form.get("downloadUnlocked")==="on"}),"Assignment settings saved.");}
  async function addProgress(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await run(()=>request("POST",{action:"progress",title:form.get("title"),details:form.get("details"),progress:Number(form.get("progress")),status:form.get("status")}),"Progress update published.");e.currentTarget.reset();}
  async function sendComment(e:React.FormEvent){e.preventDefault();if(!comment.trim())return;await run(()=>request("POST",{action:"comment",message:comment}),"Comment sent.");setComment("");}
  async function upload(){if(!uploadFile)return;if(uploadFile.size>TWENTY_FIVE_MB){setNotice({type:"error",text:"Admin files must be 25 MB or smaller."});return;}await run(async()=>{const file=await uploadPrivateFile({file:uploadFile,scope:uploadKind==="preview"?"admin-preview":"admin-final",assignmentId});await request("POST",{action:"registerFile",kind:uploadKind,file});},`${uploadKind==="preview"?"Preview":"Final file"} uploaded.`);setUploadFile(null);}
  async function deleteFile(fileId:string){if(!window.confirm("Delete this file permanently?"))return;await run(()=>request("POST",{action:"deleteFile",fileId}),"File deleted.");}

  if(loading)return <main className="admin-content loading"><div className="spinner"/></main>;
  if(!supabaseConfigured)return <main className="admin-content stack"><div><span className="eyebrow">Assignment management</span><h2 style={{marginTop:7}}>Supabase setup required</h2></div><div className="notice notice-info">Connect Supabase in Vercel before opening assignment records.</div><section className="panel stack"><p className="muted">Add NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY and SUPABASE_SECRET_KEY to the Production environment, then redeploy.</p><Link className="btn btn-soft btn-sm" href="/admin"><ArrowLeft size={15}/> Back to dashboard</Link></section></main>;
  if(!data)return <main className="admin-content"><div className="notice notice-error">{notice?.text||"Assignment not found."}</div></main>;

  const a=data.assignment;
  const grouped={support:data.files.filter((f:any)=>f.kind==="support"),payment:data.files.filter((f:any)=>f.kind==="payment_proof"),preview:data.files.filter((f:any)=>f.kind==="preview"),final:data.files.filter((f:any)=>f.kind==="final")};

  return <main className="admin-content stack">
    <div className="panel-title"><div><Link href="/admin" className="eyebrow"><ArrowLeft size={15}/> Back to dashboard</Link><h2 style={{marginTop:8}}>{a.assignment_title}</h2><p className="muted">{a.student_name} · {a.university} · Client ID {data.link?.client_id}</p></div><a className="btn btn-soft btn-sm" href={`/portal/${data.link?.token}`} target="_blank"><ExternalLink size={15}/> Client view</a></div>
    {notice?<div className={`notice notice-${notice.type}`}>{notice.text}</div>:null}

    <section className="stats-grid"><div className="card stat-card"><div className="number">{a.progress}%</div><div className="label">Progress</div></div><div className="card stat-card"><div className="number" style={{fontSize:"1.2rem"}}>{statusLabel(a.status)}</div><div className="label">Assignment status</div></div><div className="card stat-card"><div className="number" style={{fontSize:"1.2rem"}}>{statusLabel(a.payment_status)}</div><div className="label">Payment status</div></div><div className="card stat-card"><div className="number" style={{fontSize:"1.25rem"}}>{formatMoney(a.quoted_amount,a.currency)}</div><div className="label">Quoted amount</div></div></section>

    <section className="admin-grid"><div className="panel"><div className="panel-title"><div><h3>Assignment controls</h3><p className="muted small">Accept the request, set the price and control final-file access.</p></div><Save/></div><form className="form-grid" onSubmit={saveOverview}><div className="field"><label htmlFor="assignment-status">Status</label><select id="assignment-status" className="select" name="status" defaultValue={a.status}>{STATUS_OPTIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div className="field"><label htmlFor="assignment-progress">Progress %</label><input id="assignment-progress" className="input" name="progress" type="number" min="0" max="100" defaultValue={a.progress} required/></div><div className="field"><label htmlFor="assignment-amount">Quoted amount</label><input id="assignment-amount" className="input" name="quotedAmount" type="number" min="0" step="0.01" defaultValue={a.quoted_amount??""}/></div><div className="field"><label htmlFor="assignment-currency">Currency</label><input id="assignment-currency" className="input" name="currency" autoComplete="off" defaultValue={a.currency||"LKR"} maxLength={10}/></div><div className="field full"><label htmlFor="assignment-final-message">Final message</label><textarea id="assignment-final-message" className="textarea" name="finalMessage" defaultValue={a.final_message||""} placeholder="Message shown when the work is completed."/></div><label className="checkbox-row field full"><input type="checkbox" name="downloadUnlocked" defaultChecked={a.download_unlocked}/><span>Allow client to download final files. Payment should normally be verified first.</span></label><div className="field full"><button className="btn btn-blue" disabled={busy}><Save size={17}/> Save controls</button></div></form></div>
      <div className="panel"><div className="panel-title"><div><h3>Client requirements</h3><p className="muted small">Submitted {formatDate(a.created_at)}</p></div></div><div className="detail-list"><div className="detail-row"><span>Contact</span><strong>{a.contact_number}</strong></div><div className="detail-row"><span>Email</span><strong>{a.email||"—"}</strong></div><div className="detail-row"><span>Programme</span><strong>{a.programme||"—"}</strong></div><div className="detail-row"><span>Module</span><strong>{a.module_name||"—"}</strong></div><div className="detail-row"><span>Service</span><strong>{a.service_type}</strong></div><div className="detail-row"><span>Deadline</span><strong>{formatDate(a.deadline)}</strong></div><div className="detail-row"><span>Group</span><strong>{a.is_group?`${a.group_members} members`:"No"}</strong></div></div><div style={{marginTop:18}}><strong>Description</strong><p className="muted" style={{whiteSpace:"pre-wrap",marginTop:6}}>{a.description}</p>{a.special_instructions?<><strong>Special instructions</strong><p className="muted" style={{whiteSpace:"pre-wrap",marginTop:6}}>{a.special_instructions}</p></>:null}</div></div></section>

    <section className="admin-grid"><div className="panel"><div className="panel-title"><div><h3>Add progress update</h3><p className="muted small">This appears immediately in the client timeline.</p></div></div><form className="stack" onSubmit={addProgress}><div className="field"><label htmlFor="update-title">Update title</label><input id="update-title" className="input" name="title" autoComplete="off" placeholder="Research and outline completed" required/></div><div className="field"><label htmlFor="update-details">Details</label><textarea id="update-details" className="textarea" name="details" placeholder="Briefly explain what was completed and what happens next."/></div><div className="form-grid"><div className="field"><label htmlFor="update-progress">Progress %</label><input id="update-progress" className="input" name="progress" type="number" min="0" max="100" defaultValue={a.progress} required/></div><div className="field"><label htmlFor="update-status">New status</label><select id="update-status" className="select" name="status" defaultValue={a.status}>{STATUS_OPTIONS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div></div><button className="btn btn-primary" disabled={busy}>Publish update</button></form></div>
      <div className="panel"><div className="panel-title"><h3>Progress history</h3></div>{data.progress.length?<div className="timeline">{data.progress.map((item:any)=><div className="timeline-item" key={item.id}><span className="timeline-dot"/><div><strong>{item.title}</strong><p className="muted small">{item.details}</p><span className="tiny muted">{item.progress}% · {formatDate(item.created_at)}</span></div></div>)}</div>:<p className="muted">No progress updates yet.</p>}</div></section>

    <section className="admin-grid"><div className="panel"><div className="panel-title"><div><h3>Payment verification</h3><p className="muted small">Review the reference and proof before unlocking downloads.</p></div><ShieldCheck/></div><div className="detail-list"><div className="detail-row"><span>Status</span><strong>{statusLabel(a.payment_status)}</strong></div><div className="detail-row"><span>Reference</span><strong>{a.payment_reference||"Not submitted"}</strong></div><div className="detail-row"><span>Client note</span><strong>{a.payment_note||"—"}</strong></div><div className="detail-row"><span>Submitted</span><strong>{formatDate(a.payment_submitted_at)}</strong></div></div>{grouped.payment.map((file:any)=><FileRow key={file.id} file={file} onDelete={()=>deleteFile(file.id)}/>) }<div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:18}}><button className="btn btn-blue" disabled={busy||!a.payment_reference} onClick={()=>run(()=>request("POST",{action:"verifyPayment",unlock:true}),"Payment verified and downloads unlocked.")}><CheckCircle2 size={17}/> Verify & unlock</button><button className="btn btn-danger" disabled={busy} onClick={()=>run(()=>request("POST",{action:"rejectPayment",message:"The submitted payment details could not be verified. Please check the reference and submit again."}),"Payment marked as rejected.")}><XCircle size={17}/> Reject</button></div></div>
      <div className="panel"><div className="panel-title"><div><h3>Upload deliverables</h3><p className="muted small">Preview must be PDF or image. Final files remain private until unlocked.</p></div><UploadCloud/></div><div className="field"><label htmlFor="upload-purpose">File purpose</label><select id="upload-purpose" className="select" value={uploadKind} onChange={(e)=>setUploadKind(e.target.value as "preview"|"final")}><option value="preview">Watermarked preview</option><option value="final">Final downloadable file</option></select></div><div className="field" style={{marginTop:14}}><label htmlFor="deliverable-file">Select file (maximum 25 MB)</label><input id="deliverable-file" className="input" type="file" accept={uploadKind==="preview"?".pdf,.jpg,.jpeg,.png,.webp":".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip,.txt,.csv,.jpg,.jpeg,.png,.webp"} onChange={(e)=>setUploadFile(e.target.files?.[0]||null)}/></div><button className="btn btn-primary" type="button" style={{marginTop:14}} disabled={busy||!uploadFile} onClick={upload}>{busy?<Loader2 size={17}/>:<UploadCloud size={17}/>} Upload {uploadKind}</button></div></section>

    <section className="panel"><div className="panel-title"><div><h3>Files</h3><p className="muted small">All documents are stored in the private Supabase bucket.</p></div><FileLock2/></div>{(["support","preview","final"] as const).map(kind=><div key={kind} style={{marginBottom:18}}><strong>{kind==="support"?"Client support documents":kind==="preview"?"Preview files":"Final files"}</strong>{grouped[kind].length?grouped[kind].map((file:any)=><FileRow key={file.id} file={file} onDelete={kind==="support"?undefined:()=>deleteFile(file.id)}/>):<p className="muted small">No {kind} files.</p>}</div>)}</section>

    <section className="panel"><div className="panel-title"><div><h3>Client conversation</h3><p className="muted small">Use this for short questions, changes and revision notes.</p></div><MessageSquareText/></div><div className="comment-list">{data.comments.length?data.comments.map((item:any)=><div className={`comment ${item.author==="admin"?"admin":""}`} key={item.id}>{item.message}<time>{item.author==="admin"?"You":"Client"} · {formatDate(item.created_at)}</time></div>):<p className="muted">No comments yet.</p>}</div><form onSubmit={sendComment} style={{display:"flex",gap:10,marginTop:16}}><label className="sr-only" htmlFor="admin-comment">Message to client</label><input id="admin-comment" className="input" name="comment" autoComplete="off" value={comment} onChange={(e)=>setComment(e.target.value)} maxLength={1000} placeholder="Send a message to the client…"/><button className="btn btn-blue" title="Send message" disabled={busy||!comment.trim()}><Send size={18}/></button></form></section>
  </main>;
}

function FileRow({file,onDelete}:{file:any;onDelete?:()=>void}){return <div className="file-row"><div className="file-name"><strong>{file.original_name}</strong><span className="tiny muted">{statusLabel(file.kind)} · {(file.size_bytes/1024/1024).toFixed(2)} MB · {formatDate(file.created_at)}</span></div><div style={{display:"flex",gap:8}}><a className="btn btn-soft btn-sm" href={`/api/admin/files/${file.id}`}><Download size={14}/> Open</a>{onDelete?<button className="btn btn-danger btn-sm" type="button" title="Delete file" onClick={onDelete}><Trash2 size={14}/></button>:null}</div></div>}
