import type { Metadata } from "next";
import { PolicyDocument, type PolicySection } from "@/components/PolicyDocument";
import { getPublicContent } from "@/lib/data";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn how StHelp collects, uses, stores and shares client information, uploaded documents and payment references.",
  alternates: { canonical: "/privacy-policy" }
};

export const dynamic = "force-dynamic";

const sections: PolicySection[] = [
  { id: "information", title: "Information we collect", content: <><p>StHelp collects information that clients, administrators and website visitors provide or generate while using the service. This may include:</p><ul><li>names, telephone and WhatsApp numbers, email addresses and client identifiers;</li><li>university, programme, module, deadline and assignment details;</li><li>messages, revision requests, quotations and service history;</li><li>uploaded briefs, documents, images, datasets, payment slips and other files;</li><li>payment amount, method, transaction reference and verification status;</li><li>technical data such as IP address, browser type, device information, timestamps, security logs and essential cookie data; and</li><li>communications sent to StHelp by email, WhatsApp or the private client portal.</li></ul><p>Please avoid sending unnecessary sensitive personal information or third-party confidential material.</p></> },
  { id: "use", title: "How information is used", content: <><p>We use information to assess requests, prepare quotations, communicate with clients, deliver support, manage revisions, verify payments, protect preview and final files, maintain activity records, prevent misuse, troubleshoot the website and comply with legal or payment-provider obligations.</p><p>We do not sell personal information. We do not use uploaded assignment documents for unrelated public promotion without separate permission.</p></> },
  { id: "documents", title: "Uploaded documents and private portals", content: <><p>Assignment briefs, support documents, payment proofs, previews and final files are stored in restricted systems used to provide the requested service. Client portals use private links and may use additional access controls. Clients must keep portal links and access details confidential.</p><p>Authorised StHelp personnel and service providers may access files only where reasonably necessary to operate, secure or deliver the service.</p></> },
  { id: "payments", title: "Payments and PayHere", content: <><p>For bank transfers, StHelp receives the payment reference, uploaded proof and information you choose to provide for verification. When PayHere online payment is available and selected, PayHere processes the payment transaction under its own privacy and security terms.</p><p>StHelp may receive transaction identifiers, amount, currency, status and limited payer information from PayHere. StHelp does not receive or store the full card number, CVV, online-banking password, PIN or one-time passcode. Payment providers and banks may retain information as required by financial, fraud-prevention and legal obligations.</p></> },
  { id: "cookies", title: "Cookies and technical information", content: <><p>The website may use strictly necessary cookies or similar storage for administrator sessions, security and core website functionality. Hosting and security providers may create technical logs to deliver pages, detect abuse and investigate errors.</p><p>If optional analytics or marketing cookies are introduced, this policy and the website controls will be updated as appropriate.</p></> },
  { id: "sharing", title: "Service providers and disclosure", content: <><p>Information may be handled by trusted providers supporting website hosting, database and file storage, email delivery, communications, security and payments. These may include Vercel, Supabase, PayHere and any email provider enabled by StHelp. Their infrastructure may process information outside Sri Lanka subject to their safeguards and applicable law.</p><p>Information may also be disclosed where required by law, a valid regulatory or court request, to investigate fraud or security incidents, or to establish and defend legal rights. We do not disclose client work to universities or other third parties unless authorised, legally required or necessary to address serious misuse.</p></> },
  { id: "retention", title: "Retention and deletion", content: <><p>Information is retained only for as long as reasonably needed for service delivery, revisions, payment reconciliation, security, dispute handling and legal or accounting obligations. Different records may have different retention periods. Financial and transaction records may need to be kept after service files are deleted.</p><p>You may request access, correction or deletion using the business email shown in the footer. Include enough information to verify your identity and identify the relevant client record. StHelp will assess the request and delete or anonymise eligible information, but may retain records required by law, payment obligations, security needs or an unresolved dispute.</p></> },
  { id: "security", title: "Security and client responsibilities", content: <><p>StHelp uses reasonable technical and organisational safeguards, including private storage, restricted administration and protected client links. No internet service can promise absolute security. Notify StHelp promptly if you believe a portal link, account or file has been accessed without permission.</p></> },
  { id: "rights", title: "Questions and privacy requests", content: <><p>Send privacy questions, correction requests or deletion requests to the business email in the website footer. StHelp may ask for identity verification before changing or releasing information. If this policy changes materially, the updated version and effective date will be published on this page.</p></> }
];

export default async function PrivacyPolicyPage() {
  const { settings } = await getPublicContent();
  return <PolicyDocument settings={settings} eyebrow="StHelp business policies" title={<>Privacy<br/><em>policy.</em></>} summary="How StHelp handles contact details, university information, uploaded work, payment references and website data." sections={sections}/>;
}
