"use client";

import { useCallback, useEffect, useState } from "react";
import { Eye, EyeOff, Plus, Save, Trash2 } from "lucide-react";

export function ContentManager(){
  const [settings,setSettings]=useState<any>(null);const [content,setContent]=useState<any>({portfolio:[],testimonials:[]});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<{type:"success"|"error"|"info";text:string}|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const [sRes,cRes]=await Promise.all([fetch("/api/admin/settings",{cache:"no-store"}),fetch("/api/admin/content",{cache:"no-store"})]);const [s,c]=await Promise.all([sRes.json(),cRes.json()]);if(!sRes.ok)throw new Error(s.error);if(!cRes.ok)throw new Error(c.error);setSettings(s.settings);setContent(c);}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Unable to load settings."});}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
  async function run(task:()=>Promise<any>,message:string){setBusy(true);setNotice(null);try{await task();setNotice({type:"success",text:message});await load();}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Action failed."});}finally{setBusy(false);}}
  async function saveSettings(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const r=await fetch("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessName:f.get("businessName"),whatsappNumber:f.get("whatsappNumber"),bankName:f.get("bankName"),accountName:f.get("accountName"),accountNumber:f.get("accountNumber"),bankBranch:f.get("bankBranch"),paymentNote:f.get("paymentNote"),currency:f.get("currency"),supportNotice:f.get("supportNotice")})});const d=await r.json();if(!r.ok)throw new Error(d.error);},"Business and payment settings saved.");}
  async function createPortfolio(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const r=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",type:"portfolio",title:f.get("title"),category:f.get("category"),description:f.get("description"),imageUrl:f.get("imageUrl"),sortOrder:Number(f.get("sortOrder")),isPublished:true})});const d=await r.json();if(!r.ok)throw new Error(d.error);},"Portfolio item added.");e.currentTarget.reset();}
  async function createTestimonial(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{const r=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",type:"testimonial",customerName:f.get("customerName"),university:f.get("university"),rating:Number(f.get("rating")),feedback:f.get("feedback"),isPublished:true})});const d=await r.json();if(!r.ok)throw new Error(d.error);},"Testimonial added.");e.currentTarget.reset();}
  async function contentAction(body:any,message:string){await run(async()=>{const r=await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);},message);}
  if(loading)return <main className="admin-content loading"><div className="spinner"/></main>;
  return <main className="admin-content stack"><div><span className="eyebrow">Website management</span><h2 style={{marginTop:7}}>Content and settings</h2><p className="muted">Update WhatsApp, bank details, public work examples and customer feedback.</p></div>{notice?<div className={`notice notice-${notice.type}`}>{notice.text}</div>:null}
    {settings?<section className="panel"><div className="panel-title"><div><h3>Business and payment settings</h3><p className="muted small">These details appear on the public website and active client dashboards.</p></div><Save/></div><form className="form-grid" onSubmit={saveSettings}><div className="field"><label>Business name</label><input className="input" name="businessName" defaultValue={settings.business_name} required/></div><div className="field"><label>WhatsApp number</label><input className="input" name="whatsappNumber" defaultValue={settings.whatsapp_number} placeholder="94782067550" required/></div><div className="field"><label>Bank name</label><input className="input" name="bankName" defaultValue={settings.bank_name} required/></div><div className="field"><label>Account name</label><input className="input" name="accountName" defaultValue={settings.account_name} required/></div><div className="field"><label>Account number</label><input className="input" name="accountNumber" defaultValue={settings.account_number} required/></div><div className="field"><label>Branch</label><input className="input" name="bankBranch" defaultValue={settings.bank_branch} required/></div><div className="field"><label>Currency</label><input className="input" name="currency" defaultValue={settings.currency} required/></div><div className="field full"><label>Payment note</label><textarea className="textarea" name="paymentNote" defaultValue={settings.payment_note} required/></div><div className="field full"><label>Academic support notice</label><textarea className="textarea" name="supportNotice" defaultValue={settings.support_notice} required/></div><div className="field full"><button className="btn btn-blue" disabled={busy}><Save size={17}/> Save settings</button></div></form></section>:null}
    <section className="admin-grid"><div className="panel"><div className="panel-title"><div><h3>Add previous work</h3><p className="muted small">Use an image URL or leave it empty for the default visual.</p></div><Plus/></div><form className="stack" onSubmit={createPortfolio}><div className="form-grid"><div className="field"><label>Title</label><input className="input" name="title" required/></div><div className="field"><label>Category</label><input className="input" name="category" required/></div><div className="field full"><label>Description</label><textarea className="textarea" name="description" required/></div><div className="field full"><label>Image URL</label><input className="input" type="url" name="imageUrl" placeholder="https://..."/></div><div className="field"><label>Sort order</label><input className="input" type="number" name="sortOrder" defaultValue="0"/></div></div><button className="btn btn-primary" disabled={busy}>Add work item</button></form></div>
      <div className="panel"><div className="panel-title"><div><h3>Add customer feedback</h3><p className="muted small">Client-submitted feedback also appears below for approval.</p></div><Plus/></div><form className="stack" onSubmit={createTestimonial}><div className="form-grid"><div className="field"><label>Customer name</label><input className="input" name="customerName" required/></div><div className="field"><label>University</label><input className="input" name="university"/></div><div className="field"><label>Rating</label><select className="select" name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} stars</option>)}</select></div><div className="field full"><label>Feedback</label><textarea className="textarea" name="feedback" required/></div></div><button className="btn btn-primary" disabled={busy}>Add testimonial</button></form></div></section>
    <section className="panel"><div className="panel-title"><h3>Previous work items</h3></div>{content.portfolio.map((item:any)=><div className="file-row" key={item.id}><div className="file-name"><strong>{item.title}</strong><span className="tiny muted">{item.category} · {item.is_published?"Published":"Hidden"}</span></div><div style={{display:"flex",gap:8}}><button className="btn btn-soft btn-sm" onClick={()=>contentAction({action:"toggle",type:"portfolio",id:item.id,isPublished:!item.is_published},item.is_published?"Item hidden.":"Item published.")}>{item.is_published?<EyeOff size={14}/>:<Eye size={14}/>}</button><button className="btn btn-danger btn-sm" onClick={()=>window.confirm("Delete this work item?")&&contentAction({action:"delete",type:"portfolio",id:item.id},"Item deleted.")}><Trash2 size={14}/></button></div></div>)}{!content.portfolio.length?<p className="muted">No work examples.</p>:null}</section>
    <section className="panel"><div className="panel-title"><h3>Testimonials and pending feedback</h3></div>{content.testimonials.map((item:any)=><div className="file-row" key={item.id}><div className="file-name"><strong>{item.customer_name} · {"★".repeat(item.rating)}</strong><span className="tiny muted">{item.feedback} · {item.is_published?"Published":"Waiting / hidden"}</span></div><div style={{display:"flex",gap:8}}><button className="btn btn-soft btn-sm" onClick={()=>contentAction({action:"toggle",type:"testimonial",id:item.id,isPublished:!item.is_published},item.is_published?"Feedback hidden.":"Feedback published.")}>{item.is_published?<EyeOff size={14}/>:<Eye size={14}/>}</button><button className="btn btn-danger btn-sm" onClick={()=>window.confirm("Delete this testimonial?")&&contentAction({action:"delete",type:"testimonial",id:item.id},"Testimonial deleted.")}><Trash2 size={14}/></button></div></div>)}{!content.testimonials.length?<p className="muted">No testimonials.</p>:null}</section>
  </main>;
}
