import type { Metadata } from "next";
import { PolicyDocument, type PolicySection } from "@/components/PolicyDocument";
import { getPublicContent } from "@/lib/data";

export const metadata: Metadata = {
  title: "Business Terms and Conditions",
  description: "Read StHelp's quotation, payment, delivery, revision, client responsibility and academic-integrity terms.",
  alternates: { canonical: "/terms-and-conditions" }
};

export const dynamic = "force-dynamic";

const sections: PolicySection[] = [
  { id: "agreement", title: "Agreement and eligibility", content: <><p>These terms govern requests placed with StHelp through this website, a private client portal, WhatsApp or another agreed channel. By accepting a quotation, making payment or instructing StHelp to begin, the client agrees to these terms and the related quotation.</p><p>You must provide accurate information and have legal capacity to purchase the service. If you are under 18, a parent or legal guardian must approve the request and payment.</p></> },
  { id: "services", title: "Nature of the service", content: <><p>StHelp provides digital tutoring, editing, research guidance, technical project support, formatting, data assistance, presentation support and related learning services. The exact deliverables are those stated in the accepted quotation or written confirmation.</p><p>StHelp does not promise a particular grade, academic outcome, employment outcome, software performance outside the confirmed requirements, or acceptance by an institution. Services do not replace the client&apos;s own learning, judgment or responsibility.</p></> },
  { id: "quotes", title: "Quotations and acceptance", content: <><p>A quotation is prepared after reviewing the available brief, deliverables, deadline and complexity. Unless stated otherwise, a quotation is valid for 7 calendar days. It becomes binding when the client accepts it through the portal or in writing and completes any required payment.</p><p>Prices are normally stated in Sri Lankan Rupees (LKR). A quotation may require full payment or a stated deposit before work begins. StHelp may decline a request before acceptance where the scope, deadline, integrity concerns or available resources make delivery unsuitable.</p></> },
  { id: "payments", title: "Payments and verification", content: <><p>Available methods may include direct bank transfer with payment-slip upload and, after activation, secure online checkout processed by PayHere. The client portal displays the methods available for a particular request. Bank payments remain pending until StHelp verifies the reference or proof. PayHere payments remain pending until StHelp receives and validates the provider&apos;s server confirmation.</p><p>The client must pay the quoted amount using the correct client or order reference. Any bank, currency-conversion or card-provider charges are the client&apos;s responsibility unless the quotation states otherwise. Final downloadable files may remain locked until the required payment has been verified.</p><p>PayHere is an independent payment processor. StHelp remains responsible for the support service, cancellations and eligible refunds; PayHere is responsible for processing the payment transaction under its own terms.</p></> },
  { id: "delivery", title: "Delivery and deadlines", content: <><p>Delivery dates are estimates based on timely receipt of the complete brief, source material, feedback and payment. StHelp will make reasonable efforts to meet an agreed deadline but is not responsible for delays caused by missing or changed requirements, late client responses, inaccessible third-party systems, force majeure or events outside reasonable control.</p><p>If StHelp expects a material delay, we will aim to notify the client and agree on a revised delivery plan or another appropriate resolution.</p></> },
  { id: "revisions", title: "Revisions and changed requirements", content: <><p>Revisions are limited to the confirmed scope and any revision allowance stated in the quotation. Revision requests should identify the relevant requirement and be submitted through the client portal within 7 calendar days of the relevant preview or delivery unless another period was agreed.</p><p>A new topic, new dataset, increased word count, redesigned software feature, different marking criteria, substantially changed format or accelerated deadline is a changed requirement. StHelp may issue a revised price and timeline before continuing. Work already completed against the original scope remains payable.</p></> },
  { id: "responsibilities", title: "Client responsibilities", content: <><p>The client must:</p><ul><li>provide a complete and accurate brief, deadline, marking criteria and relevant materials;</li><li>respond to questions and review previews within a reasonable time;</li><li>check names, facts, calculations, citations and institution-specific requirements before submission;</li><li>have permission to share uploaded documents, datasets, images, software and third-party information;</li><li>keep portal links and final files secure; and</li><li>use the service and deliverables lawfully and in accordance with university rules.</li></ul><p>StHelp is not responsible for errors or delays caused by inaccurate, incomplete or late client information.</p></> },
  { id: "integrity", title: "Academic integrity", content: <><p>StHelp supports learning and legitimate academic development. Clients must not use the service for impersonation, live or take-home examination assistance where external help is prohibited, fabricated evidence, unauthorised access, plagiarism, contract cheating or any other breach of institutional rules.</p><p>StHelp may refuse, pause or terminate a request that appears unlawful, deceptive or inconsistent with academic integrity. The client remains responsible for understanding what assistance their institution permits and for declaring external or AI assistance where required.</p></> },
  { id: "files", title: "Files and intellectual property", content: <><p>The client retains rights in material they lawfully provide. The client grants StHelp permission to use that material only as needed to deliver and administer the service. Ownership or permitted use of custom final deliverables transfers only after full payment, subject to any third-party software, open-source licence, stock asset, dataset, template or citation restrictions identified in the work.</p><p>Protected previews are for review and revision only. Watermarks, access controls and download restrictions must not be removed or bypassed.</p></> },
  { id: "liability", title: "Service limits and liability", content: <><p>StHelp will provide the service with reasonable care based on the confirmed scope and information supplied. To the extent permitted by law, liability arising from a request is limited to the amount the client paid for that request. StHelp is not liable for indirect loss, lost grades, lost opportunities, institution penalties caused by client misuse, or failures of third-party platforms outside reasonable control.</p><p>Nothing in these terms excludes liability that cannot lawfully be excluded.</p></> },
  { id: "termination", title: "Suspension and termination", content: <><p>StHelp may suspend access or terminate a request for non-payment, abusive conduct, attempted security bypass, unlawful material, academic-integrity concerns or a material breach of these terms. Fees for work already completed remain payable. Any refund for an undelivered portion will be assessed under the Refund and Cancellation Policy.</p></> },
  { id: "law", title: "Governing law and contact", content: <><p>These terms are governed by the laws of the Democratic Socialist Republic of Sri Lanka. The parties should first try to resolve concerns through the business contact details in the footer. If a dispute cannot be resolved, it will be subject to the jurisdiction of the competent courts of Sri Lanka.</p><p>StHelp may update these terms for future requests. The version in force when a quotation is accepted will apply to that request unless a change is required by law or agreed by both parties.</p></> }
];

export default async function TermsAndConditionsPage() {
  const { settings } = await getPublicContent();
  return <PolicyDocument settings={settings} eyebrow="StHelp business policies" title={<>Terms &amp;<br/><em>conditions.</em></>} summary="The rules for quotations, payments, delivery, revisions, client responsibilities and responsible academic support." sections={sections}/>;
}
