import type { Metadata } from "next";
import { PolicyDocument, type PolicySection } from "@/components/PolicyDocument";
import { getPublicContent } from "@/lib/data";

export const metadata: Metadata = {
  title: "Refund and Cancellation Policy",
  description: "Read StHelp's cancellation, refund eligibility, duplicate-payment and refund-processing terms for digital support services.",
  alternates: { canonical: "/refund-policy" }
};

export const dynamic = "force-dynamic";

const sections: PolicySection[] = [
  { id: "scope", title: "Scope of this policy", content: <><p>This policy applies to payments made for StHelp&apos;s digital tutoring, editing, research guidance, formatting, data, software-project and related support services. Because each request is reviewed and prepared for an individual client, much of the work is customised and cannot be returned like a physical product.</p><p>Nothing in this policy limits rights that cannot lawfully be excluded under applicable Sri Lankan law.</p></> },
  { id: "cancellations", title: "Cancellations", content: <><p>You may request cancellation through your client portal or the business contact details in the footer. The outcome depends on when the request is received:</p><ul><li><strong>Before work begins:</strong> the amount paid is normally refundable, less any payment-processing charge that has already been irreversibly retained by a provider, where permitted by law.</li><li><strong>After work begins:</strong> StHelp may deduct the fair value of research, planning, consultation, drafting, development or other work already completed. Any approved refund will cover only the unperformed portion.</li><li><strong>After the agreed custom work has been completed or delivered:</strong> payments are normally non-refundable, except where the service was not supplied as agreed and StHelp cannot provide a reasonable correction.</li></ul><p>If StHelp cancels a request and cannot provide the agreed service, the client will receive a refund for the undelivered portion.</p></> },
  { id: "eligibility", title: "When a refund may be available", content: <><p>A full or partial refund may be considered when:</p><ul><li>a duplicate payment was made for the same assignment or invoice;</li><li>StHelp is unable to begin or complete the agreed service;</li><li>the delivered service materially differs from the confirmed scope and the issue cannot reasonably be corrected;</li><li>a payment was taken after a cancellation that StHelp had already accepted; or</li><li>the parties agree in writing to cancel an unperformed part of the work.</li></ul><p>A change of mind, a changed university deadline, failure to provide instructions, non-use of completed work, dissatisfaction with a grade, or a request outside the confirmed scope does not automatically qualify for a refund.</p></> },
  { id: "custom-work", title: "Completed and changed work", content: <><p>Quotes are based on the brief, deadline and deliverables available when the quote is accepted. Work completed against that scope remains chargeable. If the client changes the topic, data, required format, software features, word count, deadline or marking criteria, StHelp may issue a new quote instead of refunding work already performed.</p><p>Where an issue falls within the original scope, StHelp will normally try an appropriate correction or revision before deciding whether a refund is due.</p></> },
  { id: "duplicate", title: "Duplicate and incorrect payments", content: <><p>Verified duplicate payments will be refunded in full. If you believe the amount or reference was incorrect, contact StHelp promptly with the client ID, payment date, amount, payment reference and proof of payment. Do not publish card or bank credentials in portal messages.</p></> },
  { id: "requests", title: "How and when to request a refund", content: <><p>Submit a refund request within <strong>7 calendar days</strong> of the relevant payment or delivery, whichever is later. Include your name, client ID, payment reference, amount, reason and the resolution requested. Late requests may still be reviewed where required by law or where circumstances reasonably prevented an earlier request.</p><p>StHelp aims to review a complete request within <strong>7 business days</strong>. Additional information may be requested before a decision is made.</p></> },
  { id: "processing", title: "Refund processing", content: <><p>Approved PayHere payments will normally be returned through the original payment channel where supported. Approved bank-transfer refunds will be sent to an account verified as belonging to the payer or another account authorised in writing. StHelp will not request card passwords, PINs or one-time passcodes.</p><p>After approval, StHelp aims to initiate the refund within <strong>5 business days</strong>. The bank, card network or payment provider may require a further <strong>5–10 business days</strong> to display the funds. Processing time outside StHelp&apos;s systems is not under our control.</p></> },
  { id: "contact", title: "Refund contact", content: <><p>Use the email address or telephone number displayed in the website footer. Please contact StHelp before initiating a payment dispute so we have a reasonable opportunity to investigate duplicate, failed or disputed service payments.</p></> }
];

export default async function RefundPolicyPage() {
  const { settings } = await getPublicContent();
  return <PolicyDocument settings={settings} eyebrow="StHelp business policies" title={<>Refund &amp;<br/><em>cancellation policy.</em></>} summary="How cancellations, customised digital work, duplicate payments and approved refunds are handled." sections={sections}/>;
}
